### ISSUE TITLE
Lightblue-client does not support BigDecimals

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#157]
Snippet from metadata:
```json
            "listPrice": {
                "type": "object",
                "fields": {
                    "currencyCode": {
                        "type": "string",
                        "constraints": {
                            "required": true
                        }
                    },
                    "amount": {
                        "type": "bigdecimal",
                        "constraints": {
                            "required": true
                        }
                    }
                }
            },
```
Exception:
```java
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.math.BigDecimal out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.redhat.lightblue.myentity._1_0.MyEntity["listPrice"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:835)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BigDecimalDeserializer.deserialize(NumberDeserializers.java:603)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BigDecimalDeserializer.deserialize(NumberDeserializers.java:562)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1870)
	at com.redhat.lightblue.client.response.DefaultLightblueResponse.parseProcessed(DefaultLightblueResponse.java:173)
	... 42 more
```

**Comment by dcrissman** [comment]
The issue was elsewhere. Closing.
