### ISSUE TITLE
DefaultLightblueResponse.hasError throws NPE when parsing improper json

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-client#182]
When https status is 500 or 404 (not all cases), app server returns http page. Don't attempt to parse it as json.

```
 java.lang.NullPointerException
        at com.redhat.lightblue.client.response.DefaultLightblueResponse.hasError(DefaultLightblueResponse.java:79)
        at com.redhat.lightblue.client.response.DefaultLightblueResponse.parseProcessed(DefaultLightblueResponse.java:150)
```

**Comment by paterczm** [comment]
The case I described above works. I'm seeing that exception in mediator, perhaps it does something weird with the response to get that error.

**Comment by paterczm** [comment]
It's probably constructing DefaultLightblueResponse using DefaultLightblueResponse(ObjectMapper mapper) constructor.
