### ISSUE TITLE
Update client to handle parsing array with one item to non-array response

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#90]
Bug found in https://github.com/lightblue-platform/lightblue-migrator/issues/162. The response is valid json, so this will need to be investigated and fixed.

```
Caused by: com.redhat.lightblue.client.http.LightblueHttpClientException: Error sending lightblue request: {"query":{"field":"whenAvailableDate","op":">=","rvalue":"20150409T22:39:14.769+0000"},"projection":[{"field":"*","include":true,"recursive":true}],"sort":[{"whenAvailableDate":"$asc"}], "range": [0,0]}
        at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:137)
        at com.redhat.lightblue.client.hystrix.LightblueHystrixClient$DataTypeHystrixCommand.run(LightblueHystrixClient.java:69)
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
        ... 48 more
Caused by: com.redhat.lightblue.client.response.LightblueResponseParseException: Error parsing lightblue response: {"status":"COMPLETE","modifiedCount":0,"matchCount":30351,"processed":[{"creationDate":"20150402T13:54:05.000+0000","expectedExecutionMilliseconds":30000,"startDate":"20150409T22:00:00.000+0000","createdBy":"nmalik","_id":"termsJob_321","lastUpdatedBy":"nmalik","jobExecutions":[],"endDate":"20150409T23:00:00.000+0000","whenAvailableDate":"20150409T23:01:00.000+0000","configurationName":"terms","objectType":"migrationJob","lastUpdateDate":"20150402T13:54:05.000+0000","jobExecutions#":0}]}

        at com.redhat.lightblue.client.response.LightblueResponse.parseProcessed(LightblueResponse.java:107)
        at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:135)
        ... 50 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.redhat.lightblue.migrator.consistency.MigrationJob out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:575)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:569)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1121)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:148)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:123)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
        at com.redhat.lightblue.client.response.LightblueResponse.parseProcessed(LightblueResponse.java:105)
        ... 51 more
```

**Comment by jewzaam** [comment]
Client could try to convert to the single object if it sees there's only one element in the array.  Else throw a meaningful error.

**Comment by jewzaam** [comment]
Making this an enhancement since the client is actually doing a valid thing right now, failing when someone requests conversion of an array of documents to a single non-collection/array object.

**Comment by dcrissman** [comment]
> Client could try to convert to the single object if it sees there's only one element in the array. Else throw a meaningful error.

+1

Additionally, we could check *type.isArray()* if true proceed as normal, otherwise grab first element or throw exception.

**Comment by jewzaam** [comment]
If there are more than one element to grab I think it should fail.

**Comment by jewzaam** [comment]
This is an edge case.  But can be easily reproduced by asking for range(0, 0) which is inclusive.  Therefore you'd always get 0 or 1 items in the response.

Conditions:
- client supplies non-array class to data API

Results:
- if no items are returned, response is null
- if one item is returned, response is the one instance of the item
- if more than one item is returned, throw exception

Rational:
- client can easily add a range to restrict response to a single item
